export { default as ContactBanner } from "./ContactBgBanner.svg";
export { default as Map } from "./Map.svg";
export { default as India } from "./India.png";
export { default as US } from "./US.png";
export { default as NewsBanner } from "./NewsBanner.png";
export { default as FiveOakEvolTech } from "./FiveOak-EvolTech.jpg";
export { default as FiveOakEvolTechBanner } from "./FiveOak-Evoltech-banner.png";
export { default as ThulasiBanner } from "./ThulasiBanner.png";
export { default as ThulasiBanner1 } from "./Thulasi-Banner.png";
export { default as sampleBanner } from "./sampleBanner.png";
export { default as GregArms } from "./Greg-Banner.jpeg";
export { default as TenthYearBanner } from "./10-years-Banner.png";
export { default as TenthYearBanner1 } from "./10years-Banner.png";
export { default as ChristmasBanner } from "./ChristmasBanner.png";
export { default as DiwaliBanner } from "./DiwaliBanner.png";
export { default as AiBanner } from "./AiBanner.png";
export { default as AiBanner2} from "./AiTrainingBanner.png";